### ISSUE TITLE
Proposal to add Japanese translation 

### ISSUE THREAD

**Issue by C-ljur** [SirRandoo/better-sliders#3]
Hi, SirRandoo! Thank you for your useful slider mod.
I have made Japanese translation of BetterSliders.
May I send you a pull request?

**Comment by SirRandoo** [comment]
Sure, go for it

**Comment by C-ljur** [comment]
Thank you, I just sent it to you.

**Comment by SirRandoo** [comment]
Merged 👍🏼

**Comment by C-ljur** [comment]
It has been suggested that the translation is unusual and may be corrected at a later date.
I would like to inform you in advance for your understanding. Sorry for my inconvenience.

**Comment by SirRandoo** [comment]
No worries; take your time with the fixes.

**Comment by Djur13** [comment]
It seems that without realizing it, I was sidetracking Proxyer's translation work in progress.
If proxyer sends you a PR for the Japanese translation, please give priority to that translation over mine.
